### ISSUE TITLE
Incorrect DOCUMENT_ROOT

### ISSUE THREAD

**Issue by AlexSviridenkov** [WPPlugins/merge-minify-refresh#1]
I'm using XAMPP where wordpress is in "C:\XAMPP\apps\wordpress\htdocs" while DOCUMENT_ROOT is "C:\XAMPP\htdocs" so plugin can't find js and css 
To fix this problemi change code:

$this->root = $_SERVER["CONTEXT_DOCUMENT_ROOT"];

and 

private function fix_wp_subfolder($file_path) {
//        $file_path = preg_replace("/^(\/*+)/", "", $file_path);
		if($this->wordpressdir != '' && substr($file_path, 0, strlen($this->wordpressdir)) == $this->wordpressdir) {
			$file_path = substr($file_path, strlen($this->wordpressdir));
		}
		return $file_path;
	}

**Comment by tuefekci** [comment]
Sorry mate but this is only a git sync development of this plugin runs under https://plugins.svn.wordpress.org/merge-minify-refresh/
